server :
  port : 7100

spring :
  application :
    name : CONFIG-SERVER
    
eureka :
  register-with-eureka : true
  fetch-registry : true
  service-url :
    defaultZone : http://localhost:8761/eureka
  instance :
    hostname : localhost
