server:
  port: 8087

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/ipl
    username: 
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome To Spring Boot User Service!