spring.aapplication.name: booksread-data-loader

datadump.location:
  author: E:\Downloads\ol_dump_authors_2021-09-22.txt
  works: E:\Downloads\ol_dump_works_2021-09-22.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: ArEwmlYzudOtkZIeNBIeGpZY
      password: 2vfNXfHwUIR++oEYZpJY_2fAk9xlBSzqxAeYs5pc5XY1io3qofHQNufckrErBGYGEwU7HNLO131cH-PdZQUotlIT7ZpGb6ZJT3h4yr,P9lY-r9s16BlDG9K4,_dzfwSX
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

###Id is datacenter or cluster
astra.db:
  id: f7ac3b03-8482-4efa-8f50-95fd558c296e-1
  region: us-east4
  keyspace: main
  application.token: AstraCS:ArEwmlYzudOtkZIeNBIeGpZY:b997be90c44f76ea2ecba3379472a1299f22d255646ae23d4a7ac71ab428cc45

### Client ID
### iqKITKZkkLxHLCjAOmbthEIE

### Client Secret
### NsOPGSyCE1EfdcTnv.BpRu-hm+HdmB9PkRd9xnM.wz5aeq2uIgPjxgOd.nRPXstD_XDNemRjnk1+YZPJFf1fmozq.xMQiQnRi.6ZcTsY7ZqG7Coa5mbd0DG0JcsoHZhT

### Token
### AstraCS:iqKITKZkkLxHLCjAOmbthEIE:4b007b2e48a116ba0a776966c59215fb2543b35efa9607ef0ff7e82bf6ab0956


###ADMIN USER
### ArEwmlYzudOtkZIeNBIeGpZY
### 2vfNXfHwUIR++oEYZpJY_2fAk9xlBSzqxAeYs5pc5XY1io3qofHQNufckrErBGYGEwU7HNLO131cH-PdZQUotlIT7ZpGb6ZJT3h4yr,P9lY-r9s16BlDG9K4,_dzfwSX
### AstraCS:ArEwmlYzudOtkZIeNBIeGpZY:b997be90c44f76ea2ecba3379472a1299f22d255646ae23d4a7ac71ab428cc45