server:
  port: 9002

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot-microservices
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome To Spring Boot User Service!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans

---
spring:
  profiles: qa
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot-microservices-qa
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome To Spring Boot User Service!

---
spring:
  profiles: prod
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot-microservices-prod
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome To Spring Boot User Service!